FROM node:12
MAINTAINER Greg Taschuk
WORKDIR /home/node/hardhat-install
ADD https://raw.githubusercontent.com/nomiclabs/hardhat/master/packages/hardhat-core/sample-project/hardhat.config.js .

RUN yarn init -y
RUN yarn add --dev hardhat
RUN yarn add --dev @nomiclabs/hardhat-ethers
RUN yarn add --dev @nomiclabs/hardhat-waffle
RUN yarn
EXPOSE 8545
ENTRYPOINT ""
CMD ["yarn", "hardhat", "node"]
