// This file is automatically generated and contains assets from sei-devnet.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
  public whitelistedAssets: Address[];
}

export const jUSDT_ADDRESS = Address.fromString('0xe6C02C9D8B0cab886946f09F641afE9F8aCD92ca');
export const jUSDC_ADDRESS = Address.fromString('0xAd149B2C60C07cDB93728c4ceB4C08E9D100b981');
export const USDC_ADDRESS = Address.fromString('0xAd149B2C60C07cDB93728c4ceB4C08E9D100b981');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xe6C02C9D8B0cab886946f09F641afE9F8aCD92ca'), // jUSDT
    Address.fromString('0xAd149B2C60C07cDB93728c4ceB4C08E9D100b981'), // jUSDC
  ],
  pricingAssets: [
    Address.fromString('0x57ee725beeb991c70c53f9642f36755ec6eb2139'), // WSEI
    Address.fromString('0x18b9f230580b32819e8bfb8d5643d92884004590'), // JLY
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],

  whitelistedAssets: [
    Address.fromString('0x18b9f230580b32819e8bfb8d5643d92884004590'), // JLY
    Address.fromString('0xD0A4a86B62c01C3d6B3Bbd39c08e0dBd302c3b70'), // jBTC
    Address.fromString('0x57ee725beeb991c70c53f9642f36755ec6eb2139'), // WSEI
    Address.fromString('0x5ca70a668c1875764D87c738d62FdF7e0c227091'), // jETH
    Address.fromString('0xe6C02C9D8B0cab886946f09F641afE9F8aCD92ca'), // jUSDT
    Address.fromString('0xAd149B2C60C07cDB93728c4ceB4C08E9D100b981'), // jUSDC
    Address.fromString('0xC001bE9FaD650D669a20EBD159c2B6CECb0ff293'), // jGOLD
    Address.fromString('0xF8504bd3662a6A0719e8C22d1DFF182836fefb04'), // jTSLA
  ],
};
