// This file is automatically generated and contains assets from sepolia.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x835E81CB4a45b6338B43A7a66ba1C78900A76Ef3');
export const DAI_ADDRESS = Address.fromString('0xeF5f222c49c89a231F3aBE30114c77EE904e1e44');
export const jdUSD_ADDRESS = Address.fromString('0x96e20800fc46D450B18E61344b3B1f53EffA54f7');
export const USDT_ADDRESS = Address.fromString('0x9C84391B443ea3a48788079a5f98e2EaD55c9309');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x9e2A2E8549cFD4B52651e639351db8cf5a63800a'), // jdUSD
  ],
  pricingAssets: [
    Address.fromString('0x7b79995e5f793a07bc00c21412e50ecae098e7f9'), // WDFI
    Address.fromString('0x66ecB1eF31d9D176543Db5E306360bcF1f2f5930'), // JLY
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
