name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Codegen
        run: npm run codegen
      - name: Build
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint

  abi-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subgraph
        uses: actions/checkout@v2
        with:
          path: subgraph
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          repository: balancer-labs/balancer-core-v2
          token: ${{ secrets.PAT }}
          path: core
          ref: master
      - name: Install
        run: cd subgraph && npm ci
      - name: import abis
        run: cd subgraph && npm run import-abis
      - name: check abis
        run: cd subgraph && git diff HEAD --exit-code
env:
  CI: true
